DROP TABLE USER_INFO CASCADE CONSTRAINT;
DROP TABLE CHAR_INFO CASCADE CONSTRAINT;

CREATE TABLE USER_INFO (
ID VARCHAR2(20),
PW VARCHAR2(20) NOT NULL,
CONSTRAINT A PRIMARY KEY(ID)
);

CREATE TABLE CHAR_INFO (
ID VARCHAR2(20),
NAME VARCHAR2(20),
CONSTRAINT B PRIMARY KEY(ID, NAME),
CONSTRAINT C FOREIGN KEY(ID) REFERENCES USER_INFO(ID)
);

SELECT * FROM USER_INFO;

SELECT * FROM CHAR_INFO;