CREATE TABLE USER_INFO (
ID VARCHAR2(20),
PW VARCHAR2(20) NOT NULL,
CONSTRAINT A PRIMARY KEY(ID)
);

CREATE TABLE CHAR_INFO (
ID VARCHAR2(20),
NAME VARCHAR2(20),
CONSTRAINT B PRIMARY KEY(NAME),
CONSTRAINT C FOREIGN KEY(ID) REFERENCES USER_INFO(ID)
);

select * from char_info