create table CHAR_INFO (
ID VARCHAR2(20),
NAME VARCHAR2(20),
HITTING_POWER NUMBER(10) NOT NULL,
PITCHING_POWER NUMBER(10) NOT NULL,
ENHANCE_STATE NUMBER(10) NOT NULL,
CONSTRAINT A PRIMARY KEY(ID,NAME),
CONSTRAINT C FOREIGN KEY(ID) REFERENCES USER_INFO(ID)
);

CREATE TABLE USER_INFO(
ID VARCHAR2(20),
PW VARCHAR2(20) NOT NULL,
MONEY NUMBER(10) NOT NULL,
CONSTRAINT F PRIMARY KEY(ID)
);

CREATE TABLE USER_GRADE(
ID VARCHAR2(20),
GAME_CNT NUMBER(10) NOT NULL,
WIN_CNT NUMBER(10) NOT NULL,
LOSE_CNT NUMBER(10) NOT NULL,
TIE_CNT NUMBER(10) NOT NULL,
POINT_SUM NUMBER(10) NOT NULL,
CONSTRAINT H PRIMARY KEY(ID),
CONSTRAINT J FOREIGN KEY(ID) REFERENCES USER_INFO(ID)
);

CREATE TABLE CHAR_GRADE(
ID VARCHAR2(20),
NAME VARCHAR2(20),
STRIKE_CNT NUMBER(10) NOT NULL,
STRIKEOUT_CNT NUMBER(10) NOT NULL,
BAT_CNT NUMBER(10) NOT NULL,
ONEBASE_CNT NUMBER(10) NOT NULL,
DOUBLEBASE_CNT NUMBER(10) NOT NULL,
TRIPLE_CNT NUMBER(10) NOT NULL,
HOMERUN_CNT NUMBER(10) NOT NULL,
CONSTRAINT K PRIMARY KEY(ID,NAME),
CONSTRAINT L FOREIGN KEY(ID) REFERENCES USER_INFO(ID)
);


SELECT * FROM CHAR_GRADE;
SELECT * FROM USER_GRADE;
SELECT * FROM USER_INFO;
SELECT * FROM CHAR_INFO;

ALTER TABLE CHAR_INFO ADD NO NUMBER(10) NOT NULL;